### PR TITLE
Fix: use object literal shorthand in derive Key example

### LINKED ISSUE #309: Update subtlecrypto examples after updates to content
### What information was incorrect, unhelpful, or incomplete?

object literal shorthand used in content but not yet here

### What did you expect to see?

See https://github.com/mdn/content/pull/39657/files#diff-12e29f1ce3a1b155e75b708ef543437aaabe920f24e5cb4697e2187b11112b09

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by aliyasyeddd**
This PR updates the deriveKey example in the SubtleCrypto docs to use object literal shorthand.
The repo was already updated to use shorthand.
This keeps dom-examples consistent with the updated docs.

Fixes #309

### CODE REVIEW

File: web-crypto/derive-key/hkdf.js [hunk 1]
```diff
@@ -26,7 +26,7 @@
     return window.crypto.subtle.deriveKey(
       {
         name: "HKDF",
-        salt: salt,
+        salt,
```
Comment (bsmth) [inline web-crypto/derive-key/hkdf.js:29]: This was changed in https://github.com/mdn/content/commit/2c0f972d873ea2db5163dbcb12987847124751ad#diff-12e29f1ce3a1b155e75b708ef543437aaabe920f24e5cb4697e2187b11112b09

**Review by bsmth — CHANGES_REQUESTED** [review]
Thanks, could you also get the example in `encrypt-decrypt` where we have :

```diff
+  return window.crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, encoded);
-  return window.crypto.subtle.encrypt(
-    { name: "AES-GCM", iv: iv },
-    key,
-    encoded,
-  );
```

(`iv: iv` -> `iv`)


__edit:__ Actually, this pattern appears in other files, if you could replace them too, that would be great:

```bash
grep -r "iv: iv" ./web-crypto
./web-crypto/derive-key/ecdh.js:        iv: iv,
./web-crypto/derive-key/ecdh.js:          iv: iv,
./web-crypto/derive-key/pbkdf2.js:        iv: iv
./web-crypto/derive-key/pbkdf2.js:          iv: iv
./web-crypto/wrap-key/jwk.js:        iv: iv
./web-crypto/wrap-key/pkcs8.js:        iv: iv
./web-crypto/wrap-key/spki.js:        iv: iv
./web-crypto/unwrap-key/raw.js:        iv: iv
./web-crypto/import-key/raw.js:        iv: iv
./web-crypto/encrypt-decrypt/aes-gcm.js:        iv: iv
./web-crypto/encrypt-decrypt/aes-gcm.js:        iv: iv
```

**Review by bsmth — APPROVED** [review]
All looks fine, thanks 👍🏻
