### PR TITLE
fix(simple-service-worker): avoid HTML to appear as text

### LINKED ISSUE #191: Simple Service Worker example displays raw HTML
The doc https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#service_workers_demo says https://bncb2v.csb.app/  should look like
image
but it looks like
image

Running Chrome Version 107.0.5304.110 (Official Build) (arm64) on macOS Ventura 13.0.1 (22A400)

### PR DESCRIPTION
**Pull request by Maximaximum**
Fixes https://github.com/mdn/dom-examples/issues/191

### CODE REVIEW

File: service-worker/simple-service-worker/app.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ const createGalleryFigure = async (galleryImage) => {
     const myImage = document.createElement('img');
     const myCaption = document.createElement('caption');
     const myFigure = document.createElement('figure');
-    myCaption.textContent = `${galleryImage.name}: Taken by ${galleryImage.credit}`;
+    myCaption.innerHTML = `${galleryImage.name}: Taken by ${galleryImage.credit}`;
```
Comment (caugner) [inline service-worker/simple-service-worker/app.js:45]: Even though this works, we need to avoid [XSS](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting). Instead of assigning the unescaped `galleryImage.name` via `innerHTML`, it would be better to split this up into two `span` elements, one of which is assigned via `textContent` and the other via `innerHTML`:

```suggestion
    const myName = document.createElement('span');
    myName.textContent = `${galleryImage.name}: `;
    const myCredit = document.createElement('span');
    myCredit.innerHTML = `Taken by ${galleryImage.credit}`;
    myCaption.append(myName, myCredit);
```

Ideally, the "Taken by " prefix would even move into the data.

**Review by caugner — CHANGES_REQUESTED** [review]

**Review by pepelsbey — APPROVED** [review]
Looks good to me! Thank you both :)

**Review by caugner — APPROVED** [review]
